### ISSUE TITLE
Remover banco de dados e pycache do remoto

### ISSUE THREAD

**Issue by ruangustavo** [BrunoPereiradeSouza/Trilha_back-end#3]
Não é necessário subir o banco de dados, a não ser que você tenha intencionalmente populado com dados fictícios. Os arquivos `pycache` são utilizados pelo Python para deixar a execução mais rápida, pode remover tb.

[Gitignore para Django](https://www.toptal.com/developers/gitignore/api/python,django)
[Remove .pyc files from Git remote repository](https://stackoverflow.com/questions/26021040/remove-pyc-files-from-git-remote-repository)

**Comment by BrunoPereiradeSouza** [comment]
Resolvido!
