### ISSUE TITLE
Usar formatador de código

### ISSUE THREAD

**Issue by ruangustavo** [BrunoPereiradeSouza/Trilha_back-end#4]
Pode parecer besteira, mas roda um formatador de código pra deixar teu código mais padronizado, é importante. Eu recomendo utilizar o [Black](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) ou [Ruff](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff)

Observações:
- Deixa o "format on save" ligado para sempre que tu salve os arquivos ele formate automaticamente;
- Na primeira vez, todos os arquivos precisarão ser formatados, para facilitar teu trabalho, roda o comando do Black/Ruff via CLI:
```bash
black . --exclude 'venv'
```
Ou
```bash
black . --exclude 'venv'
```

**Comment by BrunoPereiradeSouza** [comment]
Resolvido!
