### ISSUE TITLE
Substituir `client_name` por uma FK de usuário

### ISSUE THREAD

**Issue by ruangustavo** [BrunoPereiradeSouza/Trilha_back-end#5]
Nesse trecho:
```python
class Sale(models.Model):
    product_name = models.CharField(max_length=150)
    product_price = models.FloatField()
    client_name = models.CharField(max_length=200)
```
Não é uma boa pegar o nome do cliente assim, imagina se tem mais de uma pessoa com o mesmo nome ou você quer consultar as vendas que foram realizadas para um cliente em específico. Talvez uma abordagem melhor seria criar uma change estrangeira para o usuário autenticado no momento.

**Comment by BrunoPereiradeSouza** [comment]
Resolvido!
