### ISSUE TITLE
Traduzir a aplicação pra português

### ISSUE THREAD

**Issue by ruangustavo** [BrunoPereiradeSouza/Trilha_back-end#6]
O código em inglês está excelente, é uma boa prática. Mas talvez o site ficaria melhor se estivesse em português, tanto a interface quanto as urls. Afinal, os usuários são brasileiros. No entanto, essa issue fica a seu critério, não é algo preocupante.

**Comment by BrunoPereiradeSouza** [comment]
O projeto foi traduzido para PT-BR. Eu tinha esquecido de fechar a issue kkk
